### ISSUE TITLE
Compiling of example of MySQL fails with ghc 8.2.2

### ISSUE THREAD

**Issue by nakaji-dayo** [khibino/haskell-relational-record#56]
I am trying to build `examples/HDBC/MySQL` using `LTS Haskell 10.5 (ghc-8.2.2)`
It fails with the following error when getting column information.

```
[56 of 57] Compiling Example.User     ( /Users/daishi/haskell/haskell-relational-record/examples/HDBC/MySQL/src/Example/User.hs, interpreted )

/Users/daishi/haskell/haskell-relational-record/examples/HDBC/MySQL/src/Example/User.hs:1:1: error:
    Exception when trying to run compile-time code:
      SqlError {seState = "", seNativeError = 1146, seErrorMsg = "Table 'TEST.columns' doesn't exist"}
    Code: defineTable [] "TEST" "user" [''Generic]
  |
1 | {-# LANGUAGE TemplateHaskell #-}
  | ^
```

I installed following versions of packages.
```
Cabal 2.0.1.1
HDBC 2.4.0.2
HDBC-mysql 0.7.1.0
HDBC-session 0.1.1.1
array 0.5.2.0
base 4.10.1.0
binary 0.8.5.1
bytestring 0.10.8.2
containers 0.5.10.2
convertible 1.1.1.0
deepseq 1.4.3.0
directory 1.3.0.2
dlist 0.8.0.4
filepath 1.4.1.2
ghc-boot-th 8.2.2
ghc-prim 0.5.1.1
hrr-example-HDBC-MySQL 0.1.0.0
integer-gmp 1.0.1.0
mtl 2.2.1
names-th 0.2.0.3
old-locale 1.0.0.7
old-time 1.1.0.3
persistable-record 0.6.0.0
persistable-types-HDBC-pg 0.0.1.5
pretty 1.1.3.3
process 1.6.1.0
product-isomorphic 0.0.3.1
relational-query 0.11.0.0
relational-query-HDBC 0.6.6.1
relational-record 0.2.1.2
relational-schemas 0.1.6.1
rts 1.0
sql-words 0.1.5.1
template-haskell 2.12.0.0
text 1.2.2.2
text-postgresql 0.0.2.3
th-data-compat 0.0.2.5
th-reify-compat 0.0.1.3
time 1.8.0.2
time-locale-compat 0.1.1.3
transformers 0.5.2.0
transformers-compat 0.5.1.4
unix 2.7.2.2
utf8-string 1.0.1.1
```

However, I can build with `LTS 9.21 (GHC 8.0.2)`.

I'm using mysql-5.7

----

There was an error in executing columnsQuerySQL in [getColumns'](https://github.com/khibino/haskell-relational-record/blob/362e527b9a9d171c123c51c73e1f5083481f05a5/relational-query-HDBC/src/Database/HDBC/Schema/MySQL.hs#L88), but columnsQuerySQL seems to be making the correct query.

```
> show columnsQuerySQL
SELECT ALL T0.table_schema AS f0, T0.table_name AS f1, T0. Column_name AS f2, T 0 .ordinal_position AS f3, T0. Column_default AS f4, T0.is_nullable AS f5, T0.data _ type AS f6 FROM INFORMATION SCHEMA.columns T 0 WHERE T0.table_schema =?) AND (T0.table_name =?) ORDER BY T0.ordinal_position ASC
```

**Comment by khibino** [comment]
MySQL case sensitivity may concern this issue.

Maybe you shoud try the `lower_case_table_names` MySQL system variable.

http://khibino.github.io/haskell-relational-record/faq.html#mysql-table-does-not-exist
